spring.application.name=Procedures-CafeLab

# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://cafelab-funda-server.database.windows.net:1433;database=procedures-cafelab-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# SQL Server Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Naming Strategy
spring.jpa.hibernate.naming.physical-strategy=com.acme.procedurescafelab.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7

# Flyway
spring.flyway.enabled=false